---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/planes":
    get:
      summary: list planes
      responses:
        '200':
          description: successful
    post:
      summary: create plane
      responses:
        '200':
          description: successful
  "/planes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show plane
      responses:
        '200':
          description: successful
    patch:
      summary: update plane
      responses:
        '200':
          description: successful
    put:
      summary: update plane
      responses:
        '200':
          description: successful
    delete:
      summary: delete plane
      responses:
        '200':
          description: successful
  "/user/{user_id}/reservations":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      responses:
        '200':
          description: successful
  "/user/{user_id}/reservations/{id}":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      responses:
        '200':
          description: successful
    patch:
      summary: update reservation
      responses:
        '200':
          description: successful
    put:
      summary: update reservation
      responses:
        '200':
          description: successful
    delete:
      summary: delete reservation
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
